---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Signs of multicolinearity part 1: CHECKING CORRELATION OF PREDICTOR VARIABLES (MULTICOLINEARITY). this refers to example 1 in notes

```{r}
setwd("C:/Users/ngonyo/Downloads")
dir()

murderdata = read.table("murder.txt", sep="\t", header = T)
head(murderdata)

#Let's check whether there is a significant correlation between the predictor variables: inhabit, inbelow, unemp
cor(murderdata[ , 2:4 ])

#we can see that unemp and inbelow have a very high correlation where r=.8154, meaning multicolinearity exists in the dataset. To address this, we can drop one of the variables, which we will do by creating two models one with each variable excluded, and then compare the models.
attach(murderdata)
model1 = lm(murders~inhabit+inbelow, data=murderdata)
model2 = lm(murders~inhabit+unemp, data=murderdata)
AIC(model1)
AIC(model2)

#AIC of model 2 is smaller than AIC of model1, so we drop inbelow and use unemp in the model.


```
##Signs of multicolinearity part 2: Oppsite signs in parameter estimates than what is expected. this refers to example 2 in notes

```{r}
setwd("C:/Users/ngonyo/Downloads")
dir()
cigdata = read.table("FTCCIGAR.txt", sep="\t", header = T)
head(cigdata)

#Outside of the example let's check for the correlation between predictor variable
cor(cigdata[, 1:3])

#TAR and NICOTINE have a high correlation, indicating multicolinearity. Let's drop one of them at a time and compare the models.
#Also, we could check the signs of the parameter estimates. Let's create the full model first
model = lm(CO~TAR+NICOTINE+WEIGHT, data=cigdata)
summary(model)
#As we discussed in the example 2, we expect the parameter estimates of NICOTINE and WEIGHT to be positive; as increasing them should increase the co emission from the cigarette. However, the estimates are negative. This also indicates multicolinearity in the model.

#Since TAR and NICOTINE are highly correlated and NICOTINE has an oppsite than expected sign for the parameter estimate, we are going to drop NICOTINE from the model and check.
model1 = lm(CO~TAR+WEIGHT, data=cigdata)
summary(model1)
model2 = lm(CO~TAR, data=data)
paste("AIC of model 2 = ", AIC=(model2), sep = "")
paste("AIC of model 1 = ", AIC=(model1), sep = "")

#model 2 is better than model 1 based on AIC values
#note that this dataset is far too small to create a usable model. We are simply seeing how to check for multicolinearity.

```
#Signs of multicolinearity part 3: Using VIF (variance inflation factor) 

```{r}
#we are using the package 'car' which has vif() function to generate vif values for each predictor variable in the model. We will create the MLRM (multiple linear regression model) and pass it into the vif function
require(car) #"companion to applied regression"
setwd("C:/Users/ngonyo/Downloads")
dir()
cigdata = read.table("FTCCIGAR.txt", sep="\t", header = T)
dim(cigdata)
head(cigdata)

#Creating MLRM
cigMLRM = lm(CO~TAR+NICOTINE+WEIGHT, data=cigdata)
summary(cigMLRM)


#Pass model into vif function
vif(cigMLRM)
#passing one variable at a time:
vif(cigMLRM)[1]
vif(cigMLRM)[2]
vif(cigMLRM)[3]

paste("VIF value of TAR predictor variable : ", vif(cigMLRM)[1],sep="")

paste("VIF value of NICOTINE predictor variable : ", vif(cigMLRM)[2],sep="")
 
paste("VIF value of WEIGHT predictor variable : ", vif(cigMLRM)[3],sep="")

#example of rounding:
paste("VIF value of WEIGHT predictor variable : ", round(vif(cigMLRM)[3], 2),sep="")

#VIF (variance inflation factor) of TAR and NICOTINE are greater than 10. This suggests presence of mutlicolinearity in model

#Next let's pick the best model using AIC (Akauke information critereon, where smaller AIC is better). We will create model using all combinations of 1 and 2 variables.
model1 = lm(CO~TAR, data=cigdata)
model2 = lm(CO~NICOTINE, data=cigdata)
model3 = lm(CO~WEIGHT, data=cigdata)
model4 = lm(CO~NICOTINE+WEIGHT, data=cigdata)
model5 = lm(CO~TAR+WEIGHT, data=cigdata)

AIC(model1)
AIC(model2)
AIC(model3)
AIC(model4)
AIC(model5)

#model1, which only has TAR as predictor variable, has smallest AIC value, so for predicting CO we will use model1.  

# for loop - to be continued
#for(i in 1:5){
#  model = paste("model", i, sep="")
#  out = paste("AIC of", model, " = ", AIC(model), sep = "")
#  print(out)
#}








```