---
title: "Untitled"
author: "NGonyo"
date: "11/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

TIME SERIES DECOMPOSITION

```{r}

#We are going to learn to identify and analyze the components in a time series dataset

#We will start with the powerload dataset, which has quarterly data, meaning the frequency is 4. Note that data coll

setwd("~/Documents/MA362/datasets")
dir()
PL = read.table("PowerLoad2.txt", sep="\t",header=T)
head(PL)

#we are using the powerload variable in the dataset, which is our response variable of the time series

#Let's first decompose the powerload time series and check the components. To begin, we must specify aspects of the time series to R, and create a timeseries variable using the TTR package's ts() function
require(TTR)
TSPL = ts(PL$PowerLoad, frequency = 4, start=c(2006, 1))
plot(TSPL, ylab = "PowerLoad", col = "purple")

#Observations: we see an increasing trend and peaks every 1st and 3rd quarter, as well as valleys in the 2nd and 4th quarters. We can also see the 3rd quarter is the maximum and 2nd is the minimum every year.
#Decomposing the time series
DecomTSPL = decompose(TSPL)
DecomTSPL
plot(DecomTSPL)

#In the above plot we can see the original time series (top / 1), extracted trend (2), extracted seasonal variation (3), and random residuals (bottom / 4)
#we can now see the increasing trend clearly. we can also clearly see the quarterly changes that we noted previously in detail

```


```{r}
#Now working with births per month dataset
setwd("~/Documents/MA362/datasets")
dir()
BM = read.table("BirthsPerMonth.txt", sep="\t",header=T)
BM(PL)

TSBM = ts(BM$BirthsPerMonth, frequency = 12, start=c(2006, 1))
plot(TSPL, ylab = "PowerLoad", col = "purple")

#decompose TS
DecomTSBM = decompose(TSBM)
plot(DecomTSBM)

```

MOVING AVERAGES

```{r}
#following is code from last session
setwd("~/Documents/MA362/datasets")
dir()
PL = read.table("PowerLoad2.txt", sep="\t",header=T)
head(PL)
require(TTR)
TSPL = ts(PL$PowerLoad, frequency = 4, start=c(2006, 1))

#new code: we will be applying a moving average to the code
MAPL = SMA(TSPL, n=4)
MAPL

#Let's convert the moving average for powerload into a time series object
TMAPL = ts(MAPL, frequency = 4, start=2006)
plot(TSPL);lines(TMAPL, col="purple")

#step 1: lets create the regression line from MAPL and t=1:16
t=1:16
MAmodel = lm(TMAPL~t)
summary(MAmodel)

#step 2: bow predict for Mt-hat for t:17:20
MAhat = predict(MAmodel, newdata=data.frame(t=17:20))
MAhat

#step 3: Let's adjust for the corresponding seasonal index / 100
#F17=M17-hat * (S.I. of Q1)/100
F17 = MAhat[1]*109.8036/100
F17


#F18=M18-hat * (S.I. of Q2)/100
F18 = MAhat[2]*98.3048/100
F18

#F19=M19-hat * (S.I. of Q3)/100
F19 = MAhat[3]*122.032033/100
F19

```

EXPONENTIAL SMOOTHING

```{r}
#following is code from last session
setwd("~/Documents/MA362/datasets")
dir()
PL = read.table("PowerLoad2.txt", sep="\t",header=T)
head(PL)

require(TTR)
TSPL = ts(PL$PowerLoad, frequency = 4, start=c(2006, 1))
plot(TSPL)

?HoltWinters
?SMA()
#we are going to use "Exponential smoothing" into the PowerLoad dataset. We will be using an exponential smoothing constant of 0.7. We will use the function HoltWinters() for exponential smoothing, with only alpha = exponential smoothing constant, so we need to set beta=FALSE, gamma=FALSE

EXPL = HoltWinters(TSPL, alpha = 0.7, beta = FALSE, gamma = FALSE)
plot(EXPL)

#How about we reduce the weight on the actual time series, Yt, by reducing the smoothing constant -- use alpha .2
EXPL2 = HoltWinters(TSPL, alpha = 0.2, beta = FALSE, gamma = FALSE)

EXPL$fitted[,3]
EXPL$fitted
plot(EXPL$fitted)
plot(EXPL)


```

TIME SERIES REGRESSION

```{r}
#recall that for the powerload time series, we have significant seasonal variation and also a trend. lets use both time trend and seasonality terms in the regression model

plot(DecomTSPL, col = "purple1")
RegPL = lm(PowerLoad~t+as.factor(Quarter), data=PL)
summary(RegPL)

#Next we will predict/forecast Powerload for 2010's 4 quarters. t will go from 17 to 20 for quarter 1-4
t=17:20
t
head(PL)
Quarter=1:4
RegFt=predict(RegPL, newdata=data.frame(t, as.factor(Quarter))) #use test dataset here
RegFt #these are the forecasted values for the 4 quarters of 2010

#as this is a  MLRM we cannot plot a line but we can plot the fitted values of the MLRM

#we are going to plot the fitted.values of the model on the original time series data
RegPL$fitted.values #note, these are fitted values, not forecasts. Fitted means values created from model with train data. predicted/forecasts are future values based on the model extrapolated into the future
TSReg=ts(RegPL$fitted.values, frequency = 4, start=c(2006,1))
plot(TSPL)
plot(TSPL);lines(TSReg, col="green");legend("bottomright", legend=c("PowerLoad", "RegressionFittedVals"), col=c("black", "green"), pch=c(15,16))



```
Assessing Exponential Smoothing 

```{r}

#Let's redo exponential smoothing, with alpha = .7
EXPL = HoltWinters(TSPL, alpha = NULL, beta = FALSE, gamma = FALSE) #picks best alpha level
EXPL = HoltWinters(TSPL, alpha = 0.7, beta = FALSE, gamma = FALSE) #default alpha = .7

plot(EXPL)
EXPL

#if you want to repeat a number many times
EXFt=rep(169.6877, 4)
EXFt
RegFt

#let's create a plot with EXPL, TSPL, RegPL$fitted.values

plot(EXPL)#note this already has original time series and exponential smoothing
plot(EXPL);lines(TSReg, col="green")
plot(EXPL);lines(RegPL$fitted.values, col="green")
#recall TSReg is the time series object created from the RegPL$fittedvalues


EXMAD=mean(abs(yt-EXFt))
EXMAD

EXMAPE=mean(abs((yt-EXFt)/yt))*100
EXMAPE

EXRMSE=sqrt(mean((yt-EXFt)^2))
EXRMSE

```

Assessing Holt Winters

```{r}
#Next redo HoltWinters
#recall we need forecast package installed
require(forecast)

HWPL = HoltWinters(TSPL, alpha = 0.7, beta = 0.5, gamma = 0.5)
HWPL = HoltWinters(TSPL, alpha = NULL, beta = NULL, gamma = NULL) #picks best parameter values
HWPL

HWForecast=forecast(HWPL, h=4) #forecasting with holt winters
HWForecast

HWFt = HWForecast$mean
HWFt
yt
plot(HWPL)
HWPL$fitted

#Let's calculate the forecast accuracy of HoltWinters Forecating Model.
#We need the actual values yt
#Also need the forecasted(predicted) values Ft

#Enter Actual future values into a column
TestCPI

yt=c(181.5, 175.2,195.1,189.3)
#Enter forecasted values into a column
Ft=c(180.34,170.88,200.86,187.2)
#Let's calculate MAD first

HWMAD=mean(abs(yt-HWFt))
HWMAD

HWMAPE=mean(abs((yt-HWFt)/yt))*100
HWMAPE

HWRMSE=sqrt(mean((yt-HWFt)^2))
HWRMSE

```

Assessing Time Series Regression 

```{r}
PL
#Next rego TS reg
RegPL = lm(PowerLoad~t+as.factor(Quarter), data=PL)
summary(RegPL)

#Next we will predict/forecast Powerload for 2010's 4 quarters. t will go from 17 to 20 for quarter 1-4
t=17:20
t
head(PL)
Quarter=1:4

RegPL



RegFt=predict(RegPL, newdata=data.frame(t, as.factor(Quarter))) #use test dataset here
RegFt #these are the forecasted values for the 4 quarters of 2010
#the actual future power load values are given in the example #1 in the last handout
yt=c(181.5, 175.2, 195, 198.3)

RegMAD = mean(abs(yt-RegFt))
RegMAD

RegMAPE=mean(abs((yt-RegFt)/yt))*100
RegMAPE

RegRMSE = sqrt(mean((yt-RegFt)^2))
RegRMSE
```

Plotting 3 Models on 1 plot, with legend

```{r}
#Next we will plot the TS models we created based on the train dataset
EXPL$fitted
plot(HWPL);lines(EXPL$fitted[, 1],col="blue")

TSReg=ts(RegPL$fitted.values, frequency = 4, start=c(2006))

plot(HWPL);lines(EXPL$fitted[, 1],col="blue");lines(TSReg, col="green");legend("bottomright", legend =c("HoltWinters", "Exponential Smoothing", "TSRegression"),col=c("red", "blue", "green"), pch=c(16,16,16))

```




